library(reticulate)
library(keras)
library(tensorflow)
library(tfdatasets)
library(magrittr)
library(zeallot)
library(readr)
library(tibble)
library(env.utils)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(deepR))
suppressPackageStartupMessages(library(JSGutils))

# TODO: source utils folder like Tomasz
source("utils/labels.R")
source("utils/misc.R")
source_python("python/data_tools.py")
