library(reticulate)
library(keras)
library(tensorflow)
library(tfdatasets)
library(magrittr)
library(zeallot)
library(readr)
library(tibble)
library(env.utils)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(deepR))
suppressPackageStartupMessages(library(JSGutils))


source("labels.R")
source("misc.R")
source_python("python/data_tools.py")
